DROP TABLE CHATUSER;
CREATE TABLE CHATUSER (
USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
NAME TEXT
);

DROP TABLE CHATMESSAGE;
CREATE TABLE CHATMESSAGE (
MESSAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
USER_ID BIGINT,
MESSAGE TEXT,
UPDATE_DATE BIGINT,
FOREIGN KEY (USER_ID) references CHATUSER (USER_ID)
);