CREATE DATABASE waketi DEFAULT CHARACTER SET utf8;

CREATE TABLE WORD (
WORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
POS_ID BIGINT,
WORD TEXT,
WORD_COUNT INTEGER,
TIME INTEGER);

CREATE TABLE CHAIN (
CHAIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
PREFIX01 BIGINT,
PREFIX02 BIGINT,
SUFFIX BIGINT DEFAULT NULL,
FOREIGN KEY (PREFIX01) references WORD (WORD_ID),
FOREIGN KEY (PREFIX02) references WORD (WORD_ID),
FOREIGN KEY (SUFFIX) references WORD (WORD_ID),
INDEX INDEX_PREFIX01 (PREFIX01),
INDEX INDEX_PREFIX02 (PREFIX02),
INDEX INDEX_SUFFIX (SUFFIX)
);

// test
SELECT c.prefix01, w1.word_id, w1.word,
c.prefix02, w2.word_id, w2.word,
c.safix, w3.word_id, w3.word
 FROM   chain c
 INNER JOIN word w1
 ON c.prefix01 = w1.word_id
 INNER JOIN word w2
 ON c.prefix02 = w2.word_id
 INNER JOIN word w3
 ON c.safix = w3.word_id;


