package com.pokosho.dao;

import net.java.ao.Entity;
import net.java.ao.schema.AutoIncrement;
import net.java.ao.schema.NotNull;
import net.java.ao.schema.PrimaryKey;

/**
 * 三階のマルコフ.
 * @author kaiba
 *
 */
public interface Chain extends Entity {
	@PrimaryKey
	@NotNull
	@AutoIncrement
	public Integer getChain_ID();
	public Integer getPrefix01();
	public Integer getPrefix02();
	public Integer getSuffix();
	public void setPrefix01(Integer prefix01);
	public void setPrefix02(Integer prefix02);
	public void setSafix(Integer safix);
}

/*

DROP TABLE CHAIN;

// hsqldb
CREATE TABLE CHAIN (
CHAIN_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
PREFIX01 INTEGER,
PREFIX02 INTEGER,
SUFFIX INTEGER DEFAULT NULL,
CONSTRAINT CHAIN_PK0 FOREIGN KEY(PREFIX01) REFERENCES WORD(WORD_ID),
CONSTRAINT CHAIN_PK1 FOREIGN KEY(PREFIX02) REFERENCES WORD(WORD_ID),
CONSTRAINT CHAIN_PK2 FOREIGN KEY(SUFFIX) REFERENCES WORD(WORD_ID)
);

// mysql
CREATE TABLE CHAIN (
CHAIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
PREFIX01 BIGINT,
PREFIX02 BIGINT,
SUFFIX BIGINT DEFAULT NULL,
FOREIGN KEY (PREFIX01) references WORD (WORD_ID),
FOREIGN KEY (PREFIX02) references WORD (WORD_ID),
FOREIGN KEY (SUFFIX) references WORD (WORD_ID),
INDEX INDEX_PREFIX01 (PREFIX01),
INDEX INDEX_PREFIX02 (PREFIX02),
INDEX INDEX_SUFFIX (SUFFIX)
);

*/