package com.pokosho.dao;

import net.java.ao.Entity;
import net.java.ao.schema.AutoIncrement;
import net.java.ao.schema.NotNull;
import net.java.ao.schema.PrimaryKey;

public interface Word extends Entity {
	@PrimaryKey
	@NotNull
	@AutoIncrement
	public Integer getWord_ID();
	@NotNull
	public Integer getPos_ID();
	public void setPos_ID(Integer posID);
	@NotNull
	public String getWord();
	public void setWord(String word);

	public Integer getWord_Count();
	public void setWord_Count(Integer count);

	public void setTime(Integer t);
	public Integer getTime();

}

/*

DROP TABLE WORD;
DROP INDEX WORD_INDEX;

// hsqldb
CREATE TABLE WORD (
WORD_ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
POS_ID INTEGER,
WORD VARCHAR(255),
WORD_COUNT INTEGER,
TIME INTEGER,
CONSTRAINT WORD_ID_PK PRIMARY KEY(WORD_ID)
);

CREATE INDEX WORD_INDEX  ON WORD(WORD);

// mysql
CREATE TABLE WORD (
WORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
POS_ID BIGINT,
WORD TEXT,
WORD_COUNT INTEGER,
TIME INTEGER)

*/